---
name: Translation Issue
description: Report a translation problem or suggest an improvement
title: "[Translation] "
labels: ["translation"]
body:
  - type: markdown
    attributes:
      value: |
        ## Report a translation issue

        Found a mistranslation, awkward phrasing, or missing translation?
        Let us know and we'll fix it.

  - type: input
    id: locale
    attributes:
      label: Language
      description: "Which language has the issue? (e.g. de, es, pt-BR, zh-CN, ar, fr, ja, ko)"
      placeholder: "pt-BR"
    validations:
      required: true

  - type: input
    id: area
    attributes:
      label: What is affected?
      description: "Pattern content or UI strings (navigation, buttons, labels, footer)?"
      placeholder: "Pattern content"
    validations:
      required: true

  - type: input
    id: pattern
    attributes:
      label: Pattern slug (if applicable)
      description: "The pattern ID, e.g. `type-inference-with-var`. Leave blank for UI string issues."
      placeholder: "type-inference-with-var"

  - type: textarea
    id: current-text
    attributes:
      label: Current text
      description: "Copy the text that is incorrect or needs improvement"
    validations:
      required: true

  - type: textarea
    id: suggested-text
    attributes:
      label: Suggested text
      description: "What should it say instead?"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: "Any extra context about why the current translation is incorrect"
